# These are supported funding model platforms

github: siddharths2710
patreon: sidsrinivas
open_collective: sidsrinivas
ko_fi: sidsrinivas
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: sidsrinivas
issuehunt: siddharths2710
otechie: sidsrinivas
custom: https://paypal.me/sidsrinivas
