# These are supported funding model platforms

#github: siddharths2710
patreon: sidsrinivas
ko_fi: sidsrinivas
liberapay: sidsrinivas
issuehunt: siddharths2710
otechie: sidsrinivas
custom: https://paypal.me/sidsrinivas