# This workflow will upload a Python Package using Twine when a release is created

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
           sudo make prereqs
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
         export TWINE_USERNAME=$TWINE_USERNAME
         export TWINE_PASSWORD=$TWINE_PASSWORD
         make publish-package
         unset TWINE_USERNAME
         unset TWINE_PASSWORD
